hmrc/essttp-frontend

- test/testsupport/DummyTest.scala
> [PP][SUPP-64] dummy test to fix build

- app/langswitch/Language.scala
- app/langswitch/Link.scala
- app/requests/RequestSupport.scala
- app/views/partials/language_selection.scala.html
- app/views/templates/Layout.scala.html
- conf/app.routes
> [PP][OPS-7229] language switcher

- app/controllers/EPayeStartController.scala
- app/controllers/EpayeNoSourceController.scala
- app/controllers/JourneyCompletionController.scala
- app/controllers/TaxOriginController.scala
- app/views/EPaye/EPayeLandingPage2.scala.html
- app/views/EPaye/EPayeStartPage.scala.html
- conf/app.routes
added back button to landing page and start page
> OPS-216[DM] Build initial landing page

- app/controllers/EpayeNoSourceController.scala
removed back button from no origin landing page
> SUPP-216[DM] Build initial landing page

- app/actions/AuthenticatedAction.scala
- app/config/AppConfig.scala
- app/testOnly/controllers/TestOnlyController.scala
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
> [PP][SUPP-274] remove redundand config and move frontend specific urls to the correct place

- build.sbt
> [PP][SUPP-291] relax sbt doc task

- app/testOnly/controllers/TestOnlyController.scala
test urls are now absolute as relative urls only work locally
> SUPP-276[DM]

- app/connectors/AuthLoginStubConnector.scala
- app/services/AuthLoginStubService.scala
- app/testOnly/controllers/TestOnlyController.scala
> SUPP-276[DM] login url points always to auth-login-stub

- README.md
- app/testOnly/controllers/StartJourneyController.scala
- app/testOnly/formsmodel/StartJourneyForm.scala
- app/testOnly/messages/Messages.scala
- app/testOnly/views/TestOnlyStartPage.scala.html
- app/util/EnumFormatter.scala
> [PP][SUPP-299] fix errors on fire starter page

- app/messages/Message.scala
- test/controllers/BankDetailsControllerSpec.scala
> [PP] private constructor so it's only possible to construct message using apply method

- app/config/AppConfig.scala
- app/connectors/TtpConnector.scala
- app/testOnly/connectors/EssttpStubConnector.scala
- conf/application.conf
- test/configs/ConfigSpec.scala
- test/testsupport/ItSpec.scala
- test/testsupport/stubs/Ttp.scala
> [JB][SUPP-378/380/381/382] update ttp urls

- app/controllers/DetermineTaxIdController.scala
- app/services/EnrolmentService.scala
- project/AppDependencies.scala
- test/testsupport/testdata/TdJsonBodies.scala
Also move determinetaxId into an enrolmentService
> [JB][SUPP-378] update the makeEmpRef method so it's correct

- app/controllers/BankDetailsController.scala
- app/messages/Messages.scala
- app/models/bars/response/BarsError.scala
- app/models/bars/response/BarsResponse.scala
- app/models/forms/BankDetailsForm.scala
- app/services/BarsService.scala
- app/services/EssttpBarsService.scala
- test/controllers/BankDetailsControllerSpec.scala
- test/models/bars/request/BarsSubjectSpec.scala
- test/testsupport/stubs/BarsStub.scala
- test/testsupport/testdata/BarsJsonResponses.scala
Ensure BARs verify is successful before confirming direct debit.
Handle AccountName too large on direct debit form.
> [dpp][SUPP-430] bugfixes and tidy-up

- conf/application.conf
> Supp 191 deskpro link

- app/actions/Actions.scala
- app/actions/BarsLockoutActionFilter.scala
- app/config/AppConfig.scala
- app/connectors/BarsConnector.scala
- app/controllers/BankDetailsController.scala
- app/messages/Messages.scala
- app/models/audit/bars/BarsAuditResponse.scala
- app/models/bars/response/BarsError.scala
- app/models/bars/response/BarsErrorResponse.scala
- app/models/bars/response/BarsResponse.scala
- app/models/forms/BankDetailsForm.scala
- app/services/BarsService.scala
- app/services/EssttpBarsService.scala
- app/util/HttpResponseUtils.scala
- app/util/QueryParameterUtils.scala
- app/views/BarsLockout.scala.html
- app/views/Views.scala
- conf/app.routes
- conf/application.conf
- project/AppDependencies.scala
- test/controllers/BankDetailsControllerSpec.scala
- test/testsupport/ItSpec.scala
- test/testsupport/stubs/BarsStub.scala
- test/testsupport/stubs/EssttpBackend.scala
- test/testsupport/testdata/BarsJsonResponses.scala
also removed the 'call both verify endpoints' logic
> [dpp]/[SUPP-446] implement lockout after too many BARs calls

- test/controllers/BankDetailsControllerSpec.scala
- test/testsupport/stubs/BarsStub.scala
- test/testsupport/stubs/EssttpBackend.scala
- test/testsupport/stubs/WireMockHelpers.scala
> [dpp]/[SUPP-483] refactor to use new WiremockHelpers

- test/controllers/BankDetailsControllerSpec.scala
- test/controllers/DatesApiControllerSpec.scala
- test/controllers/DetermineAffordabilityControllerSpec.scala
- test/controllers/DetermineAffordableQuotesControllerSpec.scala
- test/controllers/DetermineEligibilityControllerSpec.scala
- test/controllers/DetermineTaxIdControllerSpec.scala
- test/controllers/EpayeGovUkControllerSpec.scala
- test/controllers/IneligibleControllerSpec.scala
- test/controllers/InstalmentsControllerSpec.scala
- test/controllers/JourneyFinalStateCheckSpec.scala
- test/controllers/JourneyIncorrectStateRouter.scala
- test/controllers/MonthlyPaymentAmountControllerSpec.scala
- test/controllers/NotEnrolledControllerSpec.scala
- test/controllers/PaymentDayControllerSpec.scala
- test/controllers/PaymentPlanSetUpControllerSpec.scala
- test/controllers/PaymentScheduleControllerSpec.scala
- test/controllers/SignOutControllerSpec.scala
- test/controllers/SubmitArrangementControllerSpec.scala
- test/controllers/UpfrontPaymentControllerSpec.scala
- test/controllers/YourBillControllerSpec.scala
- test/testsupport/ItSpec.scala
Refactor Action stubbing (auth and bars lockout)
add a new Bars test BankDetailsController spec
> [DP][SUPP-520] controller tests tech debt

- app/messages/Messages.scala
- app/models/forms/BankDetailsForm.scala
- app/models/forms/helper/FormErrorWithFieldMessageOverrides.scala
- app/views/EnterBankDetails.scala.html
- test/controllers/BankDetailsControllerSpec.scala
make BARs for errors GDS compliant and inline with direct-debit-frontend
> [DP][SUPP-536] standardise bars error messages

- app/services/TtpService.scala
- project/AppDependencies.scala
- test/testsupport/testdata/TdAll.scala
- add lockFromDate as extra field in ArrangementRequest
- bump up play-frontend-hmrc minor version which fixes timeout dialogue bug
> [JB][SUPP-683]

- app/connectors/EmailVerificationConnector.scala
- app/controllers/EmailController.scala
- app/controllers/PaymentScheduleController.scala
- app/models/audit/eligibility/EligibilityCheckAuditDetail.scala
- app/models/audit/paymentplansetup/PaymentPlanSetUpAuditDetail.scala
- app/models/audit/planbeforesubmission/PaymentPlanBeforeSubmissionAuditDetail.scala
- app/services/AuditService.scala
- project/AppDependencies.scala
- test/controllers/DetermineEligibilityControllerSpec.scala
- test/controllers/EmailControllerSpec.scala
- test/controllers/PaymentScheduleControllerSpec.scala
- test/controllers/SubmitArrangementControllerSpec.scala
- test/testsupport/stubs/EmailVerificationStub.scala
- test/testsupport/testdata/JourneyJsonTemplates.scala
- test/testsupport/testdata/TdAll.scala
- test/testsupport/testdata/TtpJsonResponses.scala
- update existing audit events to include new fields
- change email-verification endpoints to pass journeyId to backend
> [JB][SUPP-697]

- app/views/PaymentPlanSetUpPage.scala.html
- app/views/UpfrontPaymentSummary.scala.html
- app/views/emailerrors/TooManyEmails.scala.html
- project/AppDependencies.scala
- test/controllers/PaymentPlanSetUpControllerSpec.scala
[SUPP-720] Sign out link missing focus styles
[SUPP-723] invalid br tag
[SUPP-726] Link styled as button needs to be given role='button'
> [JB] accessibility fixes
